# 서버 포트 설정
server:
  port: 8082

# database 연동 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/board2?allowPublicKeyRetrieval=true&useSSL=false
    username: findGEO
    password: Abcd123@
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update